language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: rlewallen@telogical.com
  api_key:
    secure: gvwjadJeDY3xoW1crBy/PwBNE3mwD2TK8Qe3BGOunY1SRYY1nWDFtu9j2RQbp3P6Huom3H4d8fZAVwoO5XjhYl4316lJoNw/ONLs+BOWBXRlXDmcbgvV8y15NoLngVE8T+KryuNctoL4GUjIJxYqOLOagUemfYQ+Tlc+EJwV91YOl94XTKsM7DuJJAKBCqiaak8IggMSLjQxnv1zr+6dmH/ZyIiUyiQnNIb3OStfBqYsEndIUM1NXxkIgaG5wAfF992mKa0I2h5EUMT2dwkFSkrdzYD2el2gVcND/z3lMAWD8zKeJ6MtvqvPIIVBWdHvodZA5zqfayT3fPk1tJhoeFGUCEPpr+wYOoN9HpbiGTr1GtbPNjFMFOgoNkVIvoq6pVyRdbEBv8GnYbie9c+u3m1Hch2jcn6ugnlRT5quIGM4+WiWg/KP/4pbf5fljlbnnHshURB6BRXHL7D/L814bSMdO9nx7Yb2bHojnCgHJYYXIv+uReLtd/9pQQfzkWBeyJwk9YyZMrOUHRWDRY+JauDtH2746fcC3u9mTT4bBJiGZPeN/conhwKL+8h7y6qSU1jbedZyv5DBEbP9eUGJJmgvSqlHwp+djefY8FjYTNPFIIN6WbEHyB0GqbYa02upfTxJCvsVEepYXzPJeOtp+QCmmSF3EOdbAC1wHDHYArg=
